# Default values for backend1.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
namespace: backend1
hosts:
  - nitechregular.sukruthgrandhi.com
  - sukruthgrandhi.com

image:
  repository: sukruthgrandhiofficial/backend1
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

envVariables:
  - name: DB_USER
    value: root
  - name: DB_PASSWORD
    value: nitest
  - name: DB_HOST
    value: 4.227.160.185
  - name: DB_PORT
    value: "3306"
  - name: DB_NAME
    value: test
  - name: secret
    value: 387613b80adfa6e333d9ffbaeb5dcfc4
  - name: algorithm
    value: HS256
  - name: BACKEND2_URL
    value: http://backend2-api-service.backend2